### PR TITLE
fix: enable plugin actions during indexing

### LINKED ISSUE #178: Enable plugin actions while indexing
The plugin actions currently do not require the IDE to be indexed, so the actions should be available while the IDE is doing its stuff.

### PR DESCRIPTION
**Pull request by Unthrottled**
## Motivation

Closes #178

### CODE REVIEW

File: src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.java [hunk 1]
```diff
@@ -13,7 +14,7 @@
 
 import java.util.Objects;
 
-public class MotivateMeAction extends AnAction {
+public class MotivateMeAction extends AnAction implements DumbAware {
```
Comment (Unthrottled) [inline src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.java:17]: From the java doc

```
A marker interface for the things that are allowed to run in dumb mode (when indices are in background update).
```

**Review by zd-zero — APPROVED** [review]
