### PR TITLE
fix: visual motivation alert style

### LINKED ISSUE #140: Visual Motivation Alert Style
**Describe the bug**

**To Reproduce**
Invoke any visual alerts

**Expected behavior**
No scroll should show up

**Screenshots**
89402878-15b5a900-d74a-11ea-81c1-e752b635a3ce

89403593-231f6300-d74b-11ea-907a-685a81858f9d

### PR DESCRIPTION
**Pull request by zd-zero**
Resolves #140 

Updated the balloon alert style.

Screen Shot 2020-08-05 at 21 21 07

Screen Shot 2020-08-05 at 21 21 01

A bit of a hack but we can now avoid displaying a scrollbar, changed the layout data to enable `welcomeScreen` flag.

This will then make the ballon to use text content instead of adding a pane.

https://github.com/JetBrains/intellij-community/blob/b59fbaba724d5c7e016431383a4b28963cba4ae8/platform/platform-impl/src/com/intellij/notification/impl/NotificationsManagerImpl.java#L570-L572

The consequence is not showing the balloon icon on the left side, but I think that this is a lesser consequence for avoiding scrollbars.

89402814-ffa7e880-d749-11ea-91cb-dfce12d2ba6c

https://github.com/JetBrains/intellij-community/blob/b59fbaba724d5c7e016431383a4b28963cba4ae8/platform/platform-impl/src/com/intellij/notification/impl/NotificationsManagerImpl.java#L574-L588

Now that we don't have the icon on the left side of the balloon, now made a no breaking space to the title, for the normal white space is trimmed.

As you would notice that the text under the image has fewer space, before it was:

Screen Shot 2020-08-05 at 17 57 10

Is there a reason why it has that much space?
For sometimes I get a scrollbar for the alert.
scroll

### CODE REVIEW

File: src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt [hunk 1]
```diff
@@ -27,8 +27,8 @@ object VisualMotivationAssetProvider {
         return MotivationAsset(
             textualAssetDefinition.title,
             """
-                 <img src='${visualAssetDefinition.imagePath}' alt='${visualAssetDefinition.imageAlt}' width='256' />
-                 <br><br><br><br><br><br><br><br><br><br>
+                 <img src='${visualAssetDefinition.imagePath}' alt='${visualAssetDefinition.imageAlt}' width='96px' />
```
Comment (zd-zero) [inline src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt:30]: Got used with the 8point bases.

File: src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt [hunk 2]
```diff
@@ -27,8 +27,8 @@ object VisualMotivationAssetProvider {
         return MotivationAsset(
             textualAssetDefinition.title,
             """
-                 <img src='${visualAssetDefinition.imagePath}' alt='${visualAssetDefinition.imageAlt}' width='256' />
-                 <br><br><br><br><br><br><br><br><br><br>
```
Comment (zd-zero) [inline src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt:31]: So I just removed the spacing between the text and image, as I find it has too much space. What do you think about the compact alert?

**Comment by Unthrottled** [comment]
image

image


This is what I get

```
IntelliJ IDEA 2020.2 (Ultimate Edition)
Build #IU-202.6397.94, built on July 27, 2020
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.15.0-111-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 512M
Cores: 12
Non-Bundled Plugins: io.acari.DDLCTheme, zd.zero.waifu-motivator-plugin
Current Desktop: ubuntu:GNOME
```

**Comment by zd-zero** [comment]
I get that too, it sometimes shows up, but I can't properly reproduce it, what I do to reproduce it to keep on invoking the alert. For the same gif, sometimes it's okay but sometimes it's not.

**Comment by zd-zero** [comment]
@Unthrottled updated the balloonLayoutData that is passed to balloon creation, can you try it on your end?

**Comment by Unthrottled** [comment]
Well, it's different now (but closer).

image

image


What environment are you running?

File: src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt (hunk 2 above)
Comment (Unthrottled) [reply src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt:31]: I like it! I would just like something that consistently shows the images.

**Comment by Unthrottled** [comment]
Just for fun I hard-coded the Image dimensions 

```html

 <div style="margin: 5px 5px 5px 10px; width: 320; height: 240px;" >
    <img src='${visualAssetDefinition.imagePath}' alt='${visualAssetDefinition.imageAlt}'/>
 </div>
            
```

image

Could you try that on whatever you are running?

**Comment by Unthrottled** [comment]
For me, I think the bottom space is tolerable for me.

For know I'll proceed with adding the image dimensions. We'll only add the dimension if `SystemInfo.isLinux` is true. Sound like a good hack?

File: src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt [hunk 3]
```diff
@@ -53,13 +54,24 @@ object VisualMotivationAssetProvider {
...
+                <div style="margin: 5px 5px 5px 10px;${getExtraStyles(visualAssetDefinition.imageDimensions)}" >
+                    <img src='${visualAssetDefinition.imagePath}' alt='${visualAssetDefinition.imageAlt}'/>
+                </div>
+            """.trimIndent(),
             audibleAssetDefinition.soundFile,
             arrayOf()
         )
+
+    private fun getExtraStyles(imageDimensions: ImageDimension): String =
+        if (SystemInfo.isLinux) {
```
Comment (Unthrottled) [inline src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt:68]:
```suggestion
        if (!SystemInfo.isMac) {
```

Macos is special

**Comment by Unthrottled** [comment]
I'll need to double check something. When I was on my Mac Machine. I had the same issue. I don't know if it because of my theme or what. I'll let you know the results.

**Comment by Unthrottled** [comment]
I guess it was a false alarm.

Since we are taking the image size, what are your opinions on the size of this image?

Screen Shot 2020-08-06 at 9 19 49 AM

For me it was a bit surprising, but it was a high quality gif. I like it, but do you thing it will be in the way? It does go away on blur.

**Comment by Unthrottled** [comment]
> I guess it was a false alarm.

Remember what I said before? I lied. When I was using my mac, it worked fine for a while, then it just started cutting things off. I would feel better if we just always applied the heights, regardless of platform.

**Comment by zd-zero** [comment]
> I would feel better if we just always applied the heights, regardless of platform.

Alright, let's do this, with this we can have consistent dimensions for different platforms.
