### PR TITLE
fix: decoupling audio assets from plugin bundle

### LINKED ISSUE #158: Audio Asset Decoupling
To reduce the size of the plugin, the audio assets will need to be removed from the plugin itself. Audio assets will be retrieved from a remote source and downloaded when needed for the user.

### PR DESCRIPTION
**Pull request by Unthrottled**
# Motivation

Fixes #158 

# Notes

I tried to do my best to feature parity the categories with the remote audio assets. Now we have to the ability to dynamically change and add stuff now!

### CODE REVIEW

File: src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.java [hunk 1]
```diff
@@ -22,8 +24,11 @@ public void actionPerformed( @NotNull AnActionEvent e ) {
             pluginState.isMotivateMeEnabled(),
             pluginState.isMotivateMeSoundEnabled() );
 
-        WaifuMotivation waifuMotivation = TextualMotivationFactory.getInstance().constructMotivation( e.getProject(),
```
Comment (Unthrottled) [inline src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.java:25]: I really did not want to maintain the code that handled the bundled motivation assets, so I just replaced it with temporary fix. The motivate me feature will be enhanced when #157 gets worked.

Also `TextualMotivationFactory` and it's dependencies are now un-used, should I remove?

File: src/main/java/zd/zero/waifu/motivator/plugin/assets/AssetModels.kt [hunk 2]
```diff
@@ -10,18 +15,23 @@ data class ImageDimension(
 )
 
 data class VisualMotivationAssetDefinition(
-    val imagePath: String,
+    val imagePath: String, // todo: remove this once migrated
```
Comment (Unthrottled) [inline src/main/java/zd/zero/waifu/motivator/plugin/assets/AssetModels.kt:18]: I'll eventually create an issue to address this when this can be worked. I have a couple reminders.

File: src/main/java/zd/zero/waifu/motivator/plugin/assets/AudibleAssetManager.kt [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+    emptyList()
+) {
+    override fun applyAssetUrl(
+        visualAsset: AudibleMotivationAssetDefinition,
+        assetUrl: String
+    ): AudibleMotivationAssetDefinition =
+        visualAsset.copy(path = assetUrl)
+
+    override fun convertToDefinitions(defJson: String): List<AudibleMotivationAssetDefinition> =
+        Gson().fromJson<List<AudibleMotivationAssetDefinition>>(
```
Comment (Unthrottled) [inline src/main/java/zd/zero/waifu/motivator/plugin/assets/AudibleAssetManager.kt:17]: I had to do this because of type erasure (I think).
Gson wasn't able to get the type from the generic when it was in the abstract class, so It had to be moved up to the implementing class.

File: src/main/java/zd/zero/waifu/motivator/plugin/player/DefaultWaifuSoundPlayer.java [hunk 4]
```diff
@@ -5,33 +5,31 @@
...
-    public static DefaultWaifuSoundPlayer ofFile( String fileName ) {
-        return new DefaultWaifuSoundPlayer( fileName );
+    public static DefaultWaifuSoundPlayer ofFile( Path filePath ) {
+        return new DefaultWaifuSoundPlayer( filePath );
     }
 
     @Override
     public void play() {
-        try ( InputStream soundStream = getClass().getClassLoader().getResourceAsStream( fileName ) ) {
-            if ( soundStream == null ) {
```
Comment (Unthrottled) [inline src/main/java/zd/zero/waifu/motivator/plugin/player/DefaultWaifuSoundPlayer.java:32]: `newInputStream` from `Files` returns not null.

File: src/main/java/zd/zero/waifu/motivator/plugin/player/Mp3WaifuSoundPlayer.java [hunk 5]
```diff
@@ -1,74 +1,100 @@
...
+    }
+
+    @NotNull
+    private PlaybackListener buildPlaybackListener( InputStream soundStream ) {
+        return new PlaybackListener() {
+            @Override
+            public void playbackFinished( PlaybackEvent evt ) {
+                super.playbackFinished( evt );
+                try {
+                    soundStream.close();
```
Comment (Unthrottled) [inline src/main/java/zd/zero/waifu/motivator/plugin/player/Mp3WaifuSoundPlayer.java:84]: For some reason, the input stream was being closed while it was playing. So I moved the close out of the try with resources, and put it in the finish playing callback.

File: src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.java (hunk 1 above)
Comment (zd-zero) [reply src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.java:25]: > Also TextualMotivationFactory and it's dependencies are now un-used, should I remove?

Yes please, we can retrieve the class from VCS in case we need it.

File: src/main/java/zd/zero/waifu/motivator/plugin/player/Mp3WaifuSoundPlayer.java [hunk 6]
```diff
@@ -1,74 +1,100 @@
...
+            soundStream.close();
+        }
+    }
+
+    @NotNull
+    private PlaybackListener buildPlaybackListener( InputStream soundStream ) {
+        return new PlaybackListener() {
+            @Override
+            public void playbackFinished( PlaybackEvent evt ) {
+                super.playbackFinished( evt );
```
Comment (zd-zero) [inline src/main/java/zd/zero/waifu/motivator/plugin/player/Mp3WaifuSoundPlayer.java:82]: It seems like we don't need to call `super.playbackFinished( evt );` for it doesn't contain any block of code.

File: src/main/java/zd/zero/waifu/motivator/plugin/player/Mp3WaifuSoundPlayer.java (hunk 5 above)
Comment (zd-zero) [reply src/main/java/zd/zero/waifu/motivator/plugin/player/Mp3WaifuSoundPlayer.java:84]: Maybe this happens when the alert is closed automatically, it'll stop the playing sound.

File: src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.java (hunk 1 above)
Comment (Unthrottled) [reply src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.java:25]: Dun!

File: src/main/java/zd/zero/waifu/motivator/plugin/player/Mp3WaifuSoundPlayer.java (hunk 6 above)
Comment (Unthrottled) [reply src/main/java/zd/zero/waifu/motivator/plugin/player/Mp3WaifuSoundPlayer.java]: Dun!

File: src/main/java/zd/zero/waifu/motivator/plugin/player/Mp3WaifuSoundPlayer.java (hunk 5 above)
Comment (Unthrottled) [reply src/main/java/zd/zero/waifu/motivator/plugin/player/Mp3WaifuSoundPlayer.java:83]: No, I left the alert open, it just straight up dies with this exception:

```
2020-08-24 18:16:42,396 [  80800]  ERROR - gin.player.Mp3WaifuSoundPlayer - Cannot play sound 'C:\Users\alex.DESKTOP-FO92PV5\workspace\waifu-motivator-plugin\build\idea-sandbox\config\waifuMotivationAssets\audible\celebration\waoow.mp3': Bitstream errorcode 102 
javazoom.jl.decoder.BitstreamException: Bitstream errorcode 102
	at javazoom.jl.decoder.Bitstream.newBitstreamException(Bitstream.java:413)
	at javazoom.jl.decoder.Bitstream.readFrame(Bitstream.java:300)
	at javazoom.jl.player.advanced.AdvancedPlayer.decodeFrame(AdvancedPlayer.java:152)
	at javazoom.jl.player.advanced.AdvancedPlayer.play(AdvancedPlayer.java:91)
	at javazoom.jl.player.advanced.AdvancedPlayer.play(AdvancedPlayer.java:72)
	at zd.zero.waifu.motivator.plugin.player.Mp3WaifuSoundPlayer.invokePlay(Mp3WaifuSoundPlayer.java:65)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

You can try it on your machine if you want. Put the try-with-resources back and give it a whirl.

File: src/main/java/zd/zero/waifu/motivator/plugin/player/WaifuSoundPlayerFactory.java [hunk 7]
```diff
@@ -1,54 +1,58 @@
...
+    private WaifuSoundPlayerFactory() {
+        throw new AssertionError( "Never instantiate." );
+    }
+
+    public static WaifuSoundPlayer createPlayer( Path fileName ) {
+        String extension = Optional.ofNullable( fileName )
+            .map( Path::getFileName )
+            .map( String::valueOf )
+            .filter( f -> f.contains( "." ) )
+            .map( f -> f.substring( f.lastIndexOf( '.' ) + 1 ) ).orElse( "" );
```
Comment (zd-zero) [inline src/main/java/zd/zero/waifu/motivator/plugin/player/WaifuSoundPlayerFactory.java:20]: question (_not related_):  Do you have any idea why #84 happened? Because this block of code can be changed to 
```
String extension = FilenameUtils.getExtension( fileName );
```

I'm having `NoClassDefFoundError` on other platforms.

**Review by zd-zero — APPROVED** [review]

File: src/main/java/zd/zero/waifu/motivator/plugin/player/WaifuSoundPlayerFactory.java (hunk 7 above)
Comment (Unthrottled) [reply src/main/java/zd/zero/waifu/motivator/plugin/player/WaifuSoundPlayerFactory.java:20]: image

It looks like it came bundled only with the IntelliJ platform, which would by why webstorm did the big sad.

However, that dependency is bundled with the plugin now https://github.com/zd-zero/waifu-motivator-plugin/blame/master/build.gradle#L22 so it can be changed.

Comment (Unthrottled) [reply src/main/java/zd/zero/waifu/motivator/plugin/player/WaifuSoundPlayerFactory.java:20]: Do you want to make an issue?
