### PR TITLE
fix: run at most one test notification

### LINKED ISSUE #124: Multiple Test Notifications
**Describe the bug**
The test pass notification is invoked more than once on completion, causing the plugin to dispatch more than one waifu to tell you that you did a good job. 

**To Reproduce**
Run this test: https://github.com/Unthrottled/hdd/blob/master/src/test/java/io/acari/water/WaterRepositoryTest.java

**Expected behavior**
Well you get one sound played, but you get multiple notifications the (1 more) at the bottom of the window

**Screenshots**
This is the event log and the notification after one test run.

image

**Platform (please complete the following information):**
 - Version WMP 1.0
```
IntelliJ IDEA 2020.1 (Community Edition)
Build #IC-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-109-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 512M
Cores: 12
Non-Bundled Plugins: io.acari.DDLCTheme, zd.zero.waifu-motivator-plugin
Current Desktop: ubuntu:GNOME
```

**Additional context**
Only one listener is being set, there is just more than one test pass notification being sent to the listeners.

### PR DESCRIPTION
**Pull request by Unthrottled**
# Motivation

Fixes #124 

# Description

I couldn't figure out how to wire into the actual test pass/fail in a reasonable amount of time. So I just opted to just use a hacker solution. Got a bunch of request and you don't know why? Just debounce it, it will be fine :joy:

### CODE REVIEW

File: src/main/java/zd/zero/waifu/motivator/plugin/listeners/Debouncer.kt [hunk 1]
```diff
@@ -0,0 +1,22 @@
+package zd.zero.waifu.motivator.plugin.listeners
+
+import com.intellij.util.Alarm
+
+interface Debouncer {
+    fun debounce(toDebounce: Runnable)
+}
+
+class JetbrainsDebouncer(private val debounceInterval: Int) : Debouncer {
```
Comment (zd-zero) [inline src/main/java/zd/zero/waifu/motivator/plugin/listeners/Debouncer.kt:9]: minor: I'm thinking if we can rename this to a different one, as we're already in the Jetbrains context. What do you think if we rename this to `"NotificationDebouncer"` instead? This shows that the impl of `Debouncer` is used in the Notification context, and in case we increase the usage of this impl to multiple contexts we can rename it at that time.

File: src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTester.java [hunk 2]
```diff
@@ -1,24 +1,26 @@
...
+package zd.zero.waifu.motivator.plugin.listeners;
+
+import com.intellij.openapi.project.Project;
+
+public interface WaifuUnitTester {
+
+    static WaifuUnitTester newInstance( Project project ) {
+        return new WaifuUnitTesterImpl( project.getMessageBus().connect(),
+                new WaifuUnitTesterListenerImpl( project ),
+            new JetbrainsDebouncer( 250 )
```
Comment (zd-zero) [inline src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTester.java:10]: minor: Hmmm, I suggest if we extract the magic number `250` to a local variable with `final int INTERVAL` so readers don't need to check the constructor signature for its usage.

Comment (Unthrottled) [reply src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTester.java:10]: I can change that.

You're IDE does not show the parameter hints?
image

File: src/main/java/zd/zero/waifu/motivator/plugin/listeners/Debouncer.kt (hunk 1 above)
Comment (Unthrottled) [reply src/main/java/zd/zero/waifu/motivator/plugin/listeners/Debouncer.kt]: I can rename it. 

However, I've been using interfaces as a way to separate the implementation of the interface from the actual definition. That way I could implement a debouncer using an Alarm, a Timeout, or some other thing that would work.

The fact that I used it for notifications should not be reflected in the name of this class itself. We could potentially debounce other functions in the app, not just the notifications. So it feels weird coupling the name of the class to it's current use case. It's kind of like calling a hammer a Brass Nail Hammer because I was hammering brass nails at the time :)

I just called it JetbrainsDebouncer because I used a jetbrains platform API to implement it.

But that's just me.

File: src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTester.java (hunk 2 above)
Comment (Unthrottled) [reply src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTester.java]: I also made up 250, it could probably be shorter.

File: src/main/java/zd/zero/waifu/motivator/plugin/listeners/Debouncer.kt (hunk 1 above)
Comment (zd-zero) [reply src/main/java/zd/zero/waifu/motivator/plugin/listeners/Debouncer.kt]: Sorry, I haven't made it clear. I was talking about renaming `JetbrainsDebouncer` to `NotificationDebouncer` and not the `Debouncer`.

> I just called it JetbrainsDebouncer because I used a jetbrains platform API to implement it.

Yes, this could be another argument I can accept ;)

> We could potentially debounce other functions in the app, not just the notifications. So it feels weird coupling the name of the class to it's current use case. It's kind of like calling a hammer a Brass Nail Hammer because I was hammering brass nails at the time :)

I agree with this, maybe the "Notification" was too specific, and I should've asked for something more generic like `EventDebouncer`.

I see that it was now renamed to `AlarmDebouncer`, we could definitely preserve that.

File: src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTester.java (hunk 2 above)
Comment (zd-zero) [reply src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTester.java]: Parameter hints are displayed on my IDE, but for others where it is not configured or especially when just glancing through GH PR directly.

**Comment by zd-zero** [comment]
LGTM and really thank you for the quality of the contribution ♥️
