### PR TITLE
fix: cancelled tests registers as passed event

### LINKED ISSUE #144: Cancelled Tests registers as passed event
**Describe the bug**
We should ensure that canceled events should not show a motivation event.

**To Reproduce**
Run a test and cancel it immediately, the motivation shows it as a *passed* event.

**Expected behavior**
No event should show up when users cancelled the currently running test.

### PR DESCRIPTION
**Pull request by zd-zero**
Resolves #144 

This PR changed the unit test listener topic to a more specific one which in turn gives us a better API to use and results to avoid debouncing the event. 

*P.S.* This is the product of our investigation to find a solution for #113

### CODE REVIEW

File: src/test/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImplTest.java [hunk 1]
```diff
@@ -1,47 +0,0 @@
-package zd.zero.waifu.motivator.plugin.listeners;
```
Comment (zd-zero) [inline src/test/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImplTest.java:1]: As we are now using the test topic from Intellij, this test class is now irrelevant.

File: src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java [hunk 2]
```diff
@@ -1,49 +1,37 @@
...
+                                Listener listener ) {
         this.busConnection = busConnection;
         this.listener = listener;
-        this.debouncer = debouncer;
     }
 
     @Override
     public void init() {
-        busConnection.subscribe( Notifications.TOPIC, new Notifications() {
+        busConnection.subscribe( SMTRunnerEventsListener.TEST_STATUS, new SMTRunnerEventsAdapter() {
```
Comment (zd-zero) [inline src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java:23]: Better topic to subscribe to, I still opt to programmatic topic subscription instead of a declarative one, as we're passing `project` to `WaifuUnitTester.Listener`

Comment (zd-zero) [reply src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java:23]: If you know a way to instantiate `com.intellij.openapi.project.Project` through a utility class. I tried creating a [Light service](https://jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_services.html?search=servi#light-services) with the project level which should provide a `project` instance but having errors.

Comment (Unthrottled) [reply src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java:23]: `com.intellij.openapi.project.ProjectManager` has the ability to get the open projects and default projects, is that what you are looking for?

Comment (zd-zero) [reply src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java:23]: I tried to use it but it can't give me the current project instance, maybe I'll just do it sometime soon as it'll affect many changes for this bug fix

Comment (Unthrottled) [reply src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java:23]: The `defaultProject` is not the current project?

**Comment by Unthrottled** [comment]
So I am observing that tests run on the Gradle framework don't set `wasTerminated` or `isInterrupted`, can you please confirm?

File: src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java (hunk 2 above)
Comment (zd-zero) [reply src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java:23]: Unfortunately, it is not, and as described in the docs, it is just a template project, and not the current project instance opened.

> Returns the project which is used as a template for new projects. The template project is always available, even when no other project is open. This instance is not supposed to be used for anything except template settings storage.

**Comment by zd-zero** [comment]
Oh right! I tried to use in 2 projects and missed out to test if it is terminating on Gradle.

File: src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java (hunk 2 above)
Comment (Unthrottled) [reply src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java:23]: I guess that's what I get for not reading documentation 😅

File: src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java [hunk 3]
```diff
@@ -1,54 +1,66 @@
...
+     */
+    private boolean isCancelledOnExternalProcess( @NotNull SMTestProxy.SMRootTestProxy testsRoot ) {
+        if ( !( testsRoot.getHandler() instanceof ExternalSystemProcessHandler ) ) return false;
+
+        WaifuTestPrinterAdapter printer = new WaifuTestPrinterAdapter();
+        testsRoot.printOn( printer );
+        testsRoot.flush();
+
+        return printer.getPrintableContent().toLowerCase()
+            .contains( "build cancelled" );
```
Comment (zd-zero) [inline src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java:64]: I know it's bad, please don't punish me.

**Comment by Unthrottled** [comment]
Imma take a look again 👀

**Comment by Unthrottled** [comment]
Initial testing looks good!

- [X] Maven

- [X] Gradle

- [X] Jest Tests (Webstorm)

I'll look at the code tomorrow 👍

File: src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java (hunk 3 above)
Comment (Unthrottled) [reply src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java:66]: I ain't even mad
I'm more disappointed about you not choosing to write Kotlin.
😂

File: src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java [hunk 4]
```diff
@@ -1,54 +1,68 @@
...
     public void stop() {
         this.busConnection.disconnect();
     }
 
+    /**
+     * <p>A compatibility hack method to perform checking
+     * for external processes (Gradle test execution)
+     * to check if user has cancelled the test.</p>
+     *
+     * <p>For <code>202.4357.23</code>, it should be replaced with</p>
```
Comment (Unthrottled) [inline src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java:49]: When do we plan to only support this version and above? Right now almost all of the 2020.2 products are above this version (I think). I know Android Studio is still behind.

**Comment by Unthrottled** [comment]
> P.S. This is the product of our investigation to find a solution for #113

🤔 Did you actually mean #133 ?

**Comment by Unthrottled** [comment]
Reading the added commit messages.

Very nice

**Comment by zd-zero** [comment]
> 🤔 Did you actually mean #133 ?

Yes, it is! Dat typo, my brain got drained for fixing this lol

File: src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java (hunk 4 above)
Comment (zd-zero) [reply src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java:49]: I noticed that other users don't update their IDEs as other plugins are not supported, with that in mind, for the minimum support version, I'm thinking if we start bumping it for `v1.3`, or after a couple of weeks.
Do you suggest to do it now?

File: src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java (hunk 3 above)
Comment (zd-zero) [reply src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java:66]: I'm still married to Java, I'm thinking if I can cheat with Kotlin 😂. Hope Java won't get mad at me.

File: src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java (hunk 4 above)
Comment (Unthrottled) [reply src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java:49]: > Do you suggest to do it now?

Nope, I think if you want the plugin available to a wider audience then maintaining a wider build support helps. However, I do think that eventually making `202.4357.23` the minimum version would be good to do in a near future release.

File: src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java (hunk 3 above)
Comment (Unthrottled) [reply src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterImpl.java:66]: Kotlin > Java

😂
