### PR TITLE
fix: added manual asset list sync

### LINKED ISSUE #194: Manual Asset Refresh
As a user, when I make a request for assets to be added/removed/changed to the plugin, then I expect a way to quickly consume the new changes added to the infrastructure to be used in my instance of the plugin.

### PR DESCRIPTION
**Pull request by Unthrottled**
# Motivation

Closes #194 

image

### CODE REVIEW

File: src/main/java/zd/zero/waifu/motivator/plugin/platform/UpdateAssetsListener.kt [hunk 1]
```diff
@@ -0,0 +1,11 @@
+package zd.zero.waifu.motivator.plugin.platform
+
+import com.intellij.util.messages.Topic
+
+interface UpdateAssetsListener {
+    companion object {
+        val TOPIC = Topic.create("Motivator Assets Update", UpdateAssetsListener::class.java)
+    }
+
+    fun requestUpdate()
```
Comment (zd-zero) [inline src/main/java/zd/zero/waifu/motivator/plugin/platform/UpdateAssetsListener.kt:10]: *naming-discussion*: this method is subscribed in the message publisher and would it be okay if we used the convention `on*`? wdyt about `onRequestUpdate()`?

Comment (Unthrottled) [reply src/main/java/zd/zero/waifu/motivator/plugin/platform/UpdateAssetsListener.kt:10]: Yeah I can put that back

I just saw this

```kotlin
        ApplicationManager.getApplication().messageBus
            .syncPublisher(UpdateAssetsListener.TOPIC)
            .onRequestUpdate()
```
and thought it looked weird

Comment (zd-zero) [reply src/main/java/zd/zero/waifu/motivator/plugin/platform/UpdateAssetsListener.kt]: Hmmm, for me it doesn't look that weird 😅, maybe because I'm not a native speaker as it translates to me like:
"on the event of request update" compared to a command-ish "Hey computer, request update from assets" (`requestUpdate`)

**Review by zd-zero — APPROVED** [review]

File: src/main/java/zd/zero/waifu/motivator/plugin/platform/UpdateAssetsListener.kt (hunk 1 above)
Comment (Unthrottled) [reply src/main/java/zd/zero/waifu/motivator/plugin/platform/UpdateAssetsListener.kt]: Ah what was weird to me was that I was `publishing` an event by invoking `onRequestUpdate`.
I saw the act of publishing an event to the topic by using `onRequestUpdate` weird and preferred to publish an event using `requestUpdate` which dispatched the update event. However, I didn't care that much :smile:
