### PR TITLE
chore: fix memory leak and added exit code debug log

### LINKED ISSUE #204: Small Fixes/Enhancements
- [x] Fix memory leak 
```
java.lang.RuntimeException: Memory leak detected: 'zd.zero.waifu.motivator.plugin.service.ApplicationService@567106d1' of class zd.zero.waifu.motivator.plugin.service.ApplicationService
See the cause for the corresponding Disposer.register() stacktrace:
...
```
- [x] Log Seen Exit codes.

### PR DESCRIPTION
**Pull request by Unthrottled**
# Motivation

Closes #204 

# Notes

To enable debug logging to observe the exit code in the logs, all you have to do is use the `Help | Diagnostic Tools | Debug Log Settings..`
and add the line `#zd.zero.waifu.motivator.plugin.listeners.ExitCodeListener` to it.

Should that be added to the docs?

### CODE REVIEW

File: src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.java [hunk 1]
```diff
@@ -272,11 +272,6 @@ public boolean isCellEditable( Integer info) {
 
         exitCodeTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
 
-        new CellTooltipManager(ApplicationService.INSTANCE).
-            withCellComponentProvider( CellComponentProvider.forTable( exitCodeTable )).
-            installOn( exitCodeTable );
-
-
```
Comment (zd-zero) [inline src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.java:279]: So I've been trying to figure out what this statement does is it just adds support for a tooltip mouse hover of the table right? and we don't have a tooltip, it's fine to just remove this.

**Review by zd-zero — APPROVED** [review]
