### PR TITLE
fix: able to close project before project is initalized

### LINKED ISSUE #186: Project Closing Failure
Apparently when the project closes, somehow this exception happens:

https://sentry.io/share/issue/19ba3bd484d645509b31d78dfece2507/

### PR DESCRIPTION
**Pull request by Unthrottled**
# Motivation

Closes #186 

This happened when I restarted my IDE and had many projects open before. Well I wanted to close one of the projects, before it got done indexing. So the plugin had not initialized yet.

### CODE REVIEW

File: src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java [hunk 1]
```diff
@@ -89,7 +90,8 @@ private void checkIfInGoodState( Project projectOpened, Runnable onGoodState ) {
 
     @Override
     public void projectClosing( @NotNull Project project ) {
-        if ( !pluginState.isSayonaraEnabled() || isMultipleProjectsOpened() ) return;
```
Comment (Unthrottled) [inline src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java:92]: I was curious, how come the plugin state was saved during initialization? When state changes, this will become outdated. It's not an issue at the moment, I was just wondering.

Comment (zd-zero) [reply src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java:92]: > how come the plugin state was saved during initialization? 

Can you provide more information?

Comment (Unthrottled) [reply src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java:92]: Sure! 
I was wondering why this was done
`this.pluginState = WaifuMotivatorPluginState.getPluginState();`

instead of just using ` WaifuMotivatorPluginState.getPluginState()` when state was needed. 

However, I think, I may be thinking incorrectly. Maybe the reference to the `WaifuMotivatorState ` object is the same one that gets changed as well. So maybe it is not a big deal to save the reference in an instance field.

Comment (zd-zero) [reply src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java:92]: > I was wondering why this was done

😅😅😅
I got lazy on keep calling `WaifuMotivatorPluginState.getPluginState()` so I made it as a class member.



> Maybe the reference to the WaifuMotivatorState object is the same one that gets changed as well.

You are correct as they are the same object reference pointing to the application service of the plugin state as it's a singleton.
```
ApplicationManager.getApplication().getService( WaifuMotivatorPluginState.class );
```



Now that I'm thinking about it it's unreadable to pass it as a class member because it loses its intent, so what I'm going to do is remove the `pluginState` member and always get a reference to the plugin state by always calling `WaifuMotivatorPluginState.getPluginState()`

**Comment by zd-zero** [comment]
I have pushed (a86cff6e5852bcaa4de18281b7c2a3d34f7e9fe3) the removal of `pluginState` member to make the usage and it's intent more clearer and made the `getPluginState` static import for that class, we can discuss if you agree with these changes for we can still drop the commit or modify it.

**Comment by Unthrottled** [comment]
https://github.com/zd-zero/waifu-motivator-plugin/commit/a86cff6e5852bcaa4de18281b7c2a3d34f7e9fe3 Noice, I like it!
Noice
